GPS Environment and History Obs Enhancements
mit-ll-trusted-autonomy/pyquaticus pull request #69
Opened 2024-11-12 13:47 UTC by ptcrowley

Closes #65

2024-11-12 14:07 UTC, t-gonsalves commented
Going to take a couple of days to get to this, a few questions to help me get through it faster - 
1. Have you tested the scripts that let us control the agents with arrow keys
2. I assume you initialize the field with a lat/lon reference point, how many different points have you tested? I would recommend testing a point that lies on the prime meridian (e.g. lat=45 deg, lon=180 deg) to make sure it can seamlessly go from -179 to 179 and distances make sense (i.e. the distance between (45, 179) and (45, -179) is the same as (45, 1) to (45, 3)

2024-11-12 18:01 UTC, ptcrowley commented
> Going to take a couple of days to get to this, a few questions to help me get through it faster -
> 
> 1. Have you tested the scripts that let us control the agents with arrow keys
> 2. I assume you initialize the field with a lat/lon reference point, how many different points have you tested? I would recommend testing a point that lies on the prime meridian (e.g. lat=45 deg, lon=180 deg) to make sure it can seamlessly go from -179 to 179 and distances make sense (i.e. the distance between (45, 179) and (45, -179) is the same as (45, 1) to (45, 3)

1. Yes I have tested [arrowkeys_test.py](https://github.com/mit-ll-trusted-autonomy/pyquaticus/blob/2a16d854fcd3ee3dd6a260f468a765a5bbc02bbe/test/arrowkeys_test.py) and [gps_env_test.py](https://github.com/mit-ll-trusted-autonomy/pyquaticus/blob/2a16d854fcd3ee3dd6a260f468a765a5bbc02bbe/test/gps_env_test.py)
2. There are a few different ways you can initialize the field (see [config.py](https://github.com/mit-ll-trusted-autonomy/pyquaticus/blob/2a16d854fcd3ee3dd6a260f468a765a5bbc02bbe/pyquaticus/config.py)). You can specify the northern, eastern, southern, and western bounds in lat-lon or web Mercator meters (not the same as real meters), or put the flags at a certain lat-lon and the bounds will be automatically determined. I have successfully tested 3 different locations, @mcleavLL and @br3ndanlong have each tested 1 different location successfully. I just tested going from -179 to 179 and this created some issues. I'm working on those now.

2024-12-10 19:51 UTC, ptcrowley commented
> > Going to take a couple of days to get to this, a few questions to help me get through it faster -
> > 
> > 1. Have you tested the scripts that let us control the agents with arrow keys
> > 2. I assume you initialize the field with a lat/lon reference point, how many different points have you tested? I would recommend testing a point that lies on the prime meridian (e.g. lat=45 deg, lon=180 deg) to make sure it can seamlessly go from -179 to 179 and distances make sense (i.e. the distance between (45, 179) and (45, -179) is the same as (45, 1) to (45, 3)
> 
> 1. Yes I have tested [arrowkeys_test.py](https://github.com/mit-ll-trusted-autonomy/pyquaticus/blob/2a16d854fcd3ee3dd6a260f468a765a5bbc02bbe/test/arrowkeys_test.py) and [gps_env_test.py](https://github.com/mit-ll-trusted-autonomy/pyquaticus/blob/2a16d854fcd3ee3dd6a260f468a765a5bbc02bbe/test/gps_env_test.py)
> 2. There are a few different ways you can initialize the field (see [config.py](https://github.com/mit-ll-trusted-autonomy/pyquaticus/blob/2a16d854fcd3ee3dd6a260f468a765a5bbc02bbe/pyquaticus/config.py)). You can specify the northern, eastern, southern, and western bounds in lat-lon or web Mercator meters (not the same as real meters), or put the flags at a certain lat-lon and the bounds will be automatically determined. I have successfully tested 3 different locations, @mcleavLL and @br3ndanlong have each tested 1 different location successfully. I just tested going from -179 to 179 and this created some issues. I'm working on those now.

Wrapping around the 180 longitude is now implemented. Now ready for the full review.

2024-12-17 21:50 UTC, t-gonsalves commented on pyproject.toml
In the `pyproject.toml` file I see some stuff for `black`, `ruff`, `isort` and `pytest`, but I don't see anything actually using that. We should get rid of the bloat if we're not going to use it. Otherwise, looks good to me!

2024-12-17 21:52 UTC, t-gonsalves requested changes
In the `pyproject.toml` file I see some stuff for `black`, `ruff`, `isort` and `pytest`, but I don't see anything actually using that. We should get rid of the bloat if we're not going to use it. Otherwise, looks good to me!

2024-12-18 18:54 UTC, ptcrowley commented
> In the `pyproject.toml` file I see some stuff for `black`, `ruff`, `isort` and `pytest`, but I don't see anything actually using that. We should get rid of the bloat if we're not going to use it. Otherwise, looks good to me!

Removed this stuff from `pyproject.toml`. If it looks good now I am ready to merge into main.

2024-12-18 20:05 UTC, john-kliem commented
I was running through the list of test files, and there seems to be an issue with the GPS environment water color being out of range: 

Error Occurs when using these GPS points:
config["blue_flag_home"] = (49.301673369138015, -93.52174888478079)
config["red_flag_home"] = (49.30515588662647, -93.50487665880466)

Error Encountered When Running heuristic_gps_test.py:
  File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 812, in __init__
    self.set_geom_config(config_dict)
  File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 1732, in set_geom_config
    border_contour, island_contours, land_mask = self._get_topo_geom()
  File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 3708, in _get_topo_geom
    flag_water_pixel_colors = topo_img[flag_water_xs, flag_water_ys]
IndexError: index 500 is out of bounds for axis 0 with size 428

2024-12-18 20:12 UTC, john-kliem commented
The second issue I have encountered involves the load_from_state_dict_test.py where an error occurs after  occurs after running the file for about a minute

Error:
Traceback (most recent call last):
  File "C:\Users\John\Desktop\comp_pyq\pyquaticus\test\load_from_state_dict_test.py", line 171, in <module>
    main()
  File "C:\Users\John\Desktop\comp_pyq\pyquaticus\test\load_from_state_dict_test.py", line 168, in main
    kt.begin()
  File "C:\Users\John\Desktop\comp_pyq\pyquaticus\test\load_from_state_dict_test.py", line 94, in begin
    self.obs, rewards, terminated, truncated, info = self.env.step(action_dict)
  File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 905, in step
    self._render()
  File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 4201, in _render
    self.render_buffer[self.render_ctr + 1] = np.transpose(np.array(pygame.surfarray.pixels3d(self.screen)), axes=(1, 0, 2))
IndexError: index 376 is out of bounds for axis 0 with size 376

2024-12-18 20:33 UTC, t-gonsalves approved these changes

2024-12-18 20:33 UTC, t-gonsalves commented
Pyproject looks correct now. Once the issues John raised are resolved, I'm good with merging.

2024-12-18 20:43 UTC, john-kliem commented
Another minor issue with load_from_state_dict_test.py

Replace line 99 with the following:
new_obs = self.env.reset(options = {'state_dict':self.env.state})

2024-12-18 21:38 UTC, br3ndanlong commented
> I was running through the list of test files, and there seems to be an issue with the GPS environment water color being out of range:
> 
> Error Occurs when using these GPS points: config["blue_flag_home"] = (49.301673369138015, -93.52174888478079) config["red_flag_home"] = (49.30515588662647, -93.50487665880466)
> 
> Error Encountered When Running heuristic_gps_test.py: File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 812, in **init** self.set_geom_config(config_dict) File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 1732, in set_geom_config border_contour, island_contours, land_mask = self._get_topo_geom() File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 3708, in _get_topo_geom flag_water_pixel_colors = topo_img[flag_water_xs, flag_water_ys] IndexError: index 500 is out of bounds for axis 0 with size 428

Fixed by changing ```topo_img[flag_water_xs, flag_water_ys]``` to ```topo_img[flag_water_ys, flag_water_xs]```

2024-12-19 16:23 UTC, br3ndanlong commented
> The second issue I have encountered involves the load_from_state_dict_test.py/save_video.py, where running with the save video option causes an index out-of-bounds error. I haven't looked too much into it. Seems like the buffer size isn't correct, or the game is running too long:
> 
> A quick fix could be: if (self.render_ctr+1) < len(self.render_buffer): self.render_buffer[self.render_ctr + 1] = np.transpose(np.array(pygame.surfarray.pixels3d(self.screen)), axes=(1, 0, 2)) # Update counter self.render_ctr += 1
> 
> Error: Traceback (most recent call last): File "C:\Users\John\Desktop\comp_pyq\pyquaticus\test\load_from_state_dict_test.py", line 171, in main() File "C:\Users\John\Desktop\comp_pyq\pyquaticus\test\load_from_state_dict_test.py", line 168, in main kt.begin() File "C:\Users\John\Desktop\comp_pyq\pyquaticus\test\load_from_state_dict_test.py", line 94, in begin self.obs, rewards, terminated, truncated, info = self.env.step(action_dict) File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 905, in step self._render() File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 4201, in _render self.render_buffer[self.render_ctr + 1] = np.transpose(np.array(pygame.surfarray.pixels3d(self.screen)), axes=(1, 0, 2)) IndexError: index 376 is out of bounds for axis 0 with size 376

Issue is due to numerical precision causing environments to sometimes take one more step than they should (i.e. if current time = 99.99999997 and max_time = 100, the environment thinks it is not done and will take one extra step, running over the buffer). Fix coming soon

2024-12-19 16:47 UTC, john-kliem commented
> > The second issue I have encountered involves the load_from_state_dict_test.py/save_video.py, where running with the save video option causes an index out-of-bounds error. I haven't looked too much into it. Seems like the buffer size isn't correct, or the game is running too long:
> > A quick fix could be: if (self.render_ctr+1) < len(self.render_buffer): self.render_buffer[self.render_ctr + 1] = np.transpose(np.array(pygame.surfarray.pixels3d(self.screen)), axes=(1, 0, 2)) # Update counter self.render_ctr += 1
> > Error: Traceback (most recent call last): File "C:\Users\John\Desktop\comp_pyq\pyquaticus\test\load_from_state_dict_test.py", line 171, in main() File "C:\Users\John\Desktop\comp_pyq\pyquaticus\test\load_from_state_dict_test.py", line 168, in main kt.begin() File "C:\Users\John\Desktop\comp_pyq\pyquaticus\test\load_from_state_dict_test.py", line 94, in begin self.obs, rewards, terminated, truncated, info = self.env.step(action_dict) File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 905, in step self._render() File "C:\Users\John\Desktop\comp_pyq\pyquaticus\pyquaticus\envs\pyquaticus.py", line 4201, in _render self.render_buffer[self.render_ctr + 1] = np.transpose(np.array(pygame.surfarray.pixels3d(self.screen)), axes=(1, 0, 2)) IndexError: index 376 is out of bounds for axis 0 with size 376
> 
> Issue is due to numerical precision causing environments to sometimes take one more step than they should (i.e. if current time = 99.99999997 and max_time = 100, the environment thinks it is not done and will take one extra step, running over the buffer). Fix coming soon

You might run into another issue with the depth of the images when writing out the videos to fix that I had changed the image dtype to be uint8
line 4232: out.write(cv2.cvtColor(**img.astype(np.uint8)**, cv2.COLOR_RGB2BGR))

2024-12-19 20:49 UTC, john-kliem approved these changes
All the issues with some of the test scripts have been fixed, and everything seems to be working on both Windows and Ubuntu.

2024-12-20 03:40 UTC, merged